use leptos::prelude::*;

use crate::components::page_title::*;

#[component]
pub fn FaqPage() -> impl IntoView {
    view! {
        <PageTitleComponent text="Frequent Asked Questions"/>
        <br/>

        <div class="max-w-5xl m-auto p-3">
            <div class="collapse collapse-arrow bg-base-200">
                <input type="radio" name="my-accordion-2" />
                <div class="collapse-title text-xl font-medium">
                   "How to use it?"
                </div>
                <div class="collapse-content">
                    <div class="px-5">
                        <p>"In order to use this software, you'll need to enter a string with the characters you want to generate the flashcards. For Japanese characters, you can separate the characters with the Japanese '、' for Chinese characters, you can use the Chinese '，', and for both of them you can use the traditional ','" <b>" however, you cannot mix them within the same input."</b></p>
                        <br/>
                        <p><b>"Japanese Example:"</b>" 本棚、形、空、写真"</p>
                        <div class="divider">"OR"</div>
                        <p><b>"Japanese Example:"</b>" 本棚,形,空,写真"</p>
                        <div class="divider"></div>
                        <p><b>"Chinese Example:"</b>" 中文，复习，图书馆，气温"</p>
                        <div class="divider">"OR"</div>
                        <p><b>"Chinese Example:"</b>" 中文,复习,图书馆,气温"</p>
                        <br/>
                        <p>"The software will give you a button to copy the generated flashcards."</p>
                    </div>
                </div>
            </div>
            <br/>
            <div class="collapse collapse-arrow bg-base-200">
                <input type="radio" name="my-accordion-2"/>
                <div class="collapse-title text-xl font-medium">
                    "How can I import my flashcards to Quizlet?"
                </div>
                <div class="collapse-content">
                    <ol class="list-decimal px-5">
                        <li>"Copy the generated data using the Copy Button on the WebPage"</li>
                        <li>"Open the "<a class="link-primary" href="https://quizlet.com" target="_blank">"Quizlet webpage"</a>" and within your 'Study Set' or 'Unidad de Estudio' click on Import"</li>
                        <li>"Paste the data generated by the program"</li>
                        <li>"Click on Import"</li>
                        <li>"Enjoy your flashcards!"</li>
                    </ol>
                    <br/>
                    <p>"I'm not affiliated with Quizlet nor it's company in any way."</p>
                </div>
            </div>
            <br/>
            <div class="collapse collapse-arrow bg-base-200">
                <input type="radio" name="my-accordion-2" />
                <div class="collapse-title text-xl font-medium">
                    "How can I import my flashcards to StudySmarter(Vaia)?"
                </div>
                <div class="collapse-content">
                    <ol class="list-decimal px-5">
                        <li>"Copy the generated data using the Copy Button on the WebPage"</li>
                        <li>"Open the "<a class="link-primary" href="https://app.vaia.com/home" target="_blank">"StudySmarter(Vaia) webpage"</a>" and within your 'Study Set' click on Create Flashcards and Upload Flashcards"</li>
                        <li>"Click on Import"</li>
                        <li>"Enjoy your flashcards!"</li>
                    </ol>
                    <br/>
                    <p>"I'm not affiliated with Vaia(Studysmarter) nor it's company in any way."</p>
                </div>
            </div>
            <br/>
            <div class="collapse collapse-arrow bg-base-200">
                <input type="radio" name="my-accordion-2" />
                <div class="collapse-title text-xl font-medium">
                    "About this software"
                </div>
                <div class="collapse-content">
                    <ol class="list-disc px-5">
                        <li>"This software is FLOSS and it will always be. "<a class="link-primary" href="https://github.com/mariinkys/delphinus_flashcards" target="_blank">"(GitHub Repo)"</a></li>
                        <li>"This software is possible thanks to many awesome projects, such as the "<a class="link-primary" href="https://www.edrdg.org/jmdict/j_jmdict.html" target="_blank">"JMDict Project (Japanese Dictionary)"</a>
                        and the <a class="link-primary" href="https://www.mdbg.net/chinese/dictionary?page=cedict" target="_blank">CC-CEDICT (Chinese Dictionary)</a>.</li>
                        <li>"The flashcards generated by this software may contain errors; use them at your own risk."</li>
                        <li>"This project runs under my own budget, and right now it costs me around 8€/month. If you'd like to support me or the development
                        of this project, please consider "<a class="link-primary" href="https://www.buymeacoffee.com/mariinkys" target="_blank">"Buying me a Coffee"</a></li>
                        <li>"If you have any issue and/or idea feel free to open a" <a class="link-primary" href="https://github.com/mariinkys/delphinus_flashcards/issues/new" target="_blank">" GitHub Issue "</a> "or email me at: "<a class="link-secondary" href="mailto:kysdev.owjga@aleeas.com">"kysdev.owjga@aleeas.com"</a></li>
                    </ol>
                </div>
            </div>
            <br/>
            <div class="collapse collapse-arrow bg-base-200">
                <input type="radio" name="my-accordion-2" />
                <div class="collapse-title text-xl font-medium">
                    "Acknowledgements"
                </div>
                <div class="collapse-content">
                    <p class="px-5">
                        "This site uses the " <a class="link-primary" href="https://www.edrdg.org/wiki/index.php/JMdict-EDICT_Dictionary_Project">"JMdict/EDICT" </a>
                        "and "<a class="link-primary" href="https://www.edrdg.org/wiki/index.php/KANJIDIC_Project">"KANJIDIC "</a>"dictionary files."
                        "These files are the property of the "<a class="link-primary" href="https://www.edrdg.org/">"Electronic Dictionary Research and Development Group"</a>
                        ", and are used in conformance with the Group's"<a class="link-primary" href="https://www.edrdg.org/edrdg/licence.html">" licence"</a>"."
                    </p>
                    <br/>
                    <p class="px-5">
                        "This site uses the " <a class="link-primary" href="https://www.mdbg.net/chinese/dictionary?page=cedict">"CC-CEDICT "</a>" dictionary files."
                    </p>
                </div>
            </div>
        </div>
    }
}
