<template>
   <custom-title header-text="Frequently Asked Questions"></custom-title>
   <v-expansion-panels variant="accordion">
      <v-expansion-panel>
         <v-expansion-panel-title>
            How to use it?
         </v-expansion-panel-title>
         <v-expansion-panel-text>
            <div class="px-1 mt-1">
               <p>In order to use this software, you'll need to enter a string with the characters you want to generate the
                  flashcards. For Japanese characters, you can separate the characters with the Japanese '、' for Chinese
                  characters, you can use the Chinese '，' for both of them, you can use the traditional ',' <b>however, you
                     cannot mix them within the same input.</b></p>
               <br>
               <p><b>Japanese Example:</b> 本棚、形、空、写真</p>
               <p><b>Japanese Example:</b> 本棚,形,空,写真</p>
               <br>
               <p><b>Chinese Example:</b> 中文，复习，图书馆，气温</p>
               <p><b>Chinese Example:</b> 中文,复习,图书馆,气温</p>
               <br>
               <p>The software will give you a button to copy the generated flashcards.</p>
            </div>
         </v-expansion-panel-text>
      </v-expansion-panel>
      <v-expansion-panel>
         <v-expansion-panel-title>
            How can I import my flashcards to Quizlet?
         </v-expansion-panel-title>
         <v-expansion-panel-text>
            <div class="px-1 mt-1">
               <ol class="px-4">
                  <li>Copy the generated data using the Copy Button on the WebPage</li>
                  <li>Open the <a class="text-primary" href="https://quizlet.com" target="_blank">Quizlet webpage</a> and
                     within your "Study Set" or "Unidad de Estudio" click on Import</li>
                  <li>Paste the data generated by the program</li>
                  <li><b>On the Between term and definition field, you have to enter /#*#/</b></li>
                  <li><b>On the Between cards field, you have to enter \n\#\n</b></li>
                  <li>Click on Import</li>
                  <li>Enjoy your flashcards!</li>
               </ol>
            </div>
         </v-expansion-panel-text>
      </v-expansion-panel>
      <v-expansion-panel>
         <v-expansion-panel-title>
            How can I import my flashcards to StudySmarter(Vaia)?
         </v-expansion-panel-title>
         <v-expansion-panel-text>
            <div class="px-1 mt-1">
               <ol class="px-4">
                  <li>Copy the generated data using the Copy Button on the WebPage</li>
                  <li>Open the <a class="text-primary" href="https://app.hellovaia.com" target="_blank">StudySmarter(Vaia)
                        webpage</a> and within your "Study Set" click on Create Flashcards and Upload Flashcards</li>
                  <li>Click on Import</li>
                  <li>Enjoy your flashcards!</li>
               </ol>
            </div>
         </v-expansion-panel-text>
      </v-expansion-panel>
      <v-expansion-panel>
         <v-expansion-panel-title>
            Is this all?
         </v-expansion-panel-title>
         <v-expansion-panel-text>
            <div class="px-1 mt-1">
               <p class="mb-3">As of right now, this software does the bare minimum to be somewhat useful and get you up
                  and running,
                  but it is not that useful at all. However, I want to emphasize that I have many ideas that I want to add
                  to this project that may or may not come in future versions. Here are some of the things on my to-do
                  list:</p>
               <ul class="px-4">
                  <li>Improve the speed of the Japanese flashcards generation process</li>
                  <li>Improve the ability of the program to find words in the Japanese flashcards generation process</li>
                  <li style="text-decoration: line-through;">Give the user the option to select which meaning and reading
                     they want for each word (right
                     now the flashcards get generated with all possible meanings)</li>
                  <li style="text-decoration: line-through;">Give the user the option to input the meaning and reading of
                     the words that have not been
                     found on
                     the dictionary</li>
                  <li>If a word is found more than once, ask the user which is the correct word</li>
                  <li>Improve the overall design of the application</li>
                  <li>Add the ability to make an account and save previously generated flashcards</li>
               </ul>
            </div>
         </v-expansion-panel-text>
      </v-expansion-panel>
      <v-expansion-panel>
         <v-expansion-panel-title>
            About this software
         </v-expansion-panel-title>
         <v-expansion-panel-text>
            <div class="px-1 mt-1">
               <ul class="px-4">
                  <li>This software is FOSS and it will always be. <a class="text-primary"
                        href="https://github.com/mariinkys/delphinus_flashcards" target="_blank">(GitHub Repo)</a></li>
                  <li>This software is possible thanks to many awesome projects, such as the <a class="text-primary"
                        href="https://www.edrdg.org/jmdict/j_jmdict.html" target="_blank">JMDict Project (Japanese
                        Dictionary)</a>
                     and the <a class="text-primary" href="https://www.mdbg.net/chinese/dictionary?page=cedict"
                        target="_blank">CC-CEDICT (Chinese Dictionary)</a>.</li>
                  <li>The flashcards generated by this software may contain errors; use them at your own risk.</li>
                  <li>This project runs under my own budget, and right now it costs me around 8€/month. If you'd like to
                     support me or the development
                     of this project, please consider <a class="text-primary" href="https://www.buymeacoffee.com/mariinkys"
                        target="_blank">Buying me a Coffee</a></li>
                  <li>If you have any issue and/or idea feel free to open a <a class="text-primary"
                        href="https://github.com/mariinkys/delphinus_flashcards/issues/new" target="_blank">GitHub
                        Issue</a> or email me at: <a class="text-secondary"
                        href="mailto:kysdev.owjga@aleeas.com">kysdev.owjga@aleeas.com</a></li>
               </ul>
            </div>
         </v-expansion-panel-text>
      </v-expansion-panel>
   </v-expansion-panels>
</template>

<script lang="ts">
import CustomTitle from "@/components/custom-title.vue";

export default {
   components: {
      'custom-title': CustomTitle
   },
}
</script>