<template>
   <custom-title header-text="Flashcards Generated!" />
   <v-btn @click="copyToClipboard" color="primary" block class="mt-3">Copy Result</v-btn>
   <v-row justify="center" class="mt-6">
      <v-col xs="12" sm="6" md="4">
         <v-card variant="outlined">
            <v-card-title>
               Import to Quizlet
            </v-card-title>
            <v-card-subtitle>
               See FAQ Page for more details...
            </v-card-subtitle>
            <v-card-text>
               <ol class="px-4">
                  <li>Copy the generated data using the Copy Button on the WebPage</li>
                  <li>Open the <a class="text-primary" href="https://quizlet.com" target="_blank">Quizlet webpage</a>
                     and
                     within your "Study Set" or "Unidad de Estudio" click on Import</li>
                  <li>Paste the data generated by the program</li>
                  <li>On the Between term and definition field, you have to enter /#*#/</li>
                  <li>On the Between cards field, you have to enter \n\#\n</li>
                  <li>Click on Import</li>
                  <li>Enjoy your flashcards!</li>
               </ol>
            </v-card-text>
         </v-card>
      </v-col>
      <v-col xs="12" sm="6" md="4">
         <v-card variant="outlined">
            <v-card-title>
               Import to Vaia
            </v-card-title>
            <v-card-subtitle>
               See FAQ Page for more details...
            </v-card-subtitle>
            <v-card-text>
               <ol class="px-4">
                  <ol class="px-4">
                     <li>Copy the generated data using the Copy Button on the WebPage</li>
                     <li>Open the <a class="text-primary" href="https://app.hellovaia.com"
                           target="_blank">StudySmarter(Vaia)
                           webpage</a> and within your "Study Set" click on Create Flashcards and Upload Flashcards</li>
                     <li>Click on Import</li>
                     <li>Enjoy your flashcards!</li>
                  </ol>
               </ol>
            </v-card-text>
         </v-card>
      </v-col>
   </v-row>
</template>

<script lang="ts">
import CustomTitle from "@/components/custom-title.vue";
import { useResultStore } from '@/stores/result'

export default {
   components: {
      'custom-title': CustomTitle
   },
   data: () => ({
      result: ''
   }),
   mounted() {
      const store = useResultStore()
      const storeData = store.getData
      if (storeData == null || storeData == '') this.$router.push('/')

      this.result = storeData
   },
   methods: {
      copyToClipboard() {
         try {
            navigator.clipboard.writeText(this.result);
            this.$toast.open({
               message: 'Copied to Clipboard!',
               type: 'success',
            });
         } catch (error) {
            console.error('Unable to copy to clipboard:', error);
            this.$toast.open({
               message: 'Failed to copy to clipboard.',
               type: 'error',
            });
         }
      }
   }
}
</script>