use leptos::prelude::*;

use crate::{
    components::{
        page_title::*,
        toast::{ToastMessage, ToastType},
    },
    utils::{
        create_anki_hex_file, create_quizlet_import_string, create_vaia_import_string, Flashcard,
    },
};

#[component]
pub fn ImportGeneratedFlashcards() -> impl IntoView {
    //TODO: Handle error
    let flashcards = use_context::<ReadSignal<Vec<Flashcard>>>().expect("No flashcards provided");

    let set_toast: WriteSignal<ToastMessage> = expect_context();

    let hex_anki_file = create_anki_hex_file(&flashcards.get_untracked());
    let anki_href = format!("{}{}", String::from("data:text/plain,"), hex_anki_file);

    view! {
        <PageTitleComponent text="Import your flashcards!"/>

        <div class="text-center m-auto p-2 max-w-7xl">
            <div class="sm:flex-row flex flex-col gap-2 mt-3">
                <div class="card bg-base-100 shadow-xl w-full text-left">
                    <div class="card-body">
                        <h2 class="card-title">"Import to Quizlet"</h2>
                        <ol class="px-4 list-decimal">
                            <li>"Copy the generated data using the Copy Button on the WebPage"</li>
                            <li>"Open the "<a href="https://quizlet.com/" class="link-primary">"Quizlet webpage"</a>" and within your 'Study Set' or 'Unidad de Estudio' click on Import"</li>
                            <li>"Paste the data generated by the program"</li>
                            <li>"Click on Import"</li>
                            <li>"Enjoy your flashcards!"</li>
                        </ol>
                        <br/>
                        <div class="card-actions w-full">
                            <a href="/faq" target="_blank" class="btn btn-primary w-full">"See FAQ for Details"</a>
                            <button
                                class="btn btn-accent w-full"
                                on:click=move |_| {
                                    let clipboard = window().navigator().clipboard();
                                    let _no = clipboard.write_text(&create_quizlet_import_string(&flashcards.get_untracked()));
                                    set_toast.set(ToastMessage { message: String::from("Copied to Clipboard"), toast_type: ToastType::Success, visible: true });
                                }
                            >
                                "Copy Quizlet Import String"
                            </button>
                        </div>
                    </div>
                </div>

                <div class="card bg-base-100 shadow-xl w-full text-left">
                    <div class="card-body">
                        <h2 class="card-title">"Import to Vaia"</h2>
                        <ol class="px-4 list-decimal">
                            <li>"Copy the generated data using the Copy Button on the WebPage"</li>
                            <li>"Open the "<a href="https://app.vaia.com/home" class="link-primary">"StudySmarter(Vaia) webpage"</a>" and within your 'Study Set' or 'Unidad de Estudio' click on the three dots at the top right corner and click on 'Import Flashcards'"</li>
                            <li>"Click on Import"</li>
                            <li>"Enjoy your flashcards!"</li>
                        </ol>
                        <br/>
                        <div class="card-actions w-full">
                            <a href="/faq" target="_blank" class="btn btn-primary w-full">"See FAQ for Details"</a>
                            <button
                                class="btn btn-accent w-full"
                                on:click=move |_| {
                                    let clipboard = window().navigator().clipboard();
                                    let _no = clipboard.write_text(&create_vaia_import_string(&flashcards.get_untracked()));
                                    set_toast.set(ToastMessage { message: String::from("Copied to Clipboard"), toast_type: ToastType::Success, visible: true });
                                }
                            >
                                "Copy Vaia Import String"
                            </button>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <div class="text-center m-auto p-2 max-w-7xl">
            <div class="card bg-base-100 shadow-xl w-full text-left">
                <div class="card-body">
                    <h2 class="card-title">"Import to Anki (Experimental Support)"</h2>
                    <ol class="px-4 list-decimal">
                        <li>"Download the generated Anki File"</li>
                        <li>"Use the Anki File to import your flashcards!"</li>
                    </ol>
                    <br/>
                    <div class="card-actions w-full">
                        <a
                            class="btn btn-accent w-full"
                            download="anki_export.txt"
                            href={anki_href}
                        >
                            "Download Anki File"
                        </a>
                    </div>
                </div>
            </div>
        </div>

    }
}
