use leptos::*;

use crate::components::page_title::*;

#[component]
pub fn ImportGeneratedFlashcards(import_string: String) -> impl IntoView {
    view! {
        <PageTitleComponent text="Import your flashcards!"/>

        <div class="text-center m-auto p-2 max-w-7xl">
            <button
                class="btn btn-accent w-full"
                on:click=move |_| {
                    if let Some(clipboard) = window().navigator().clipboard() {
                        //TODO: Notifications
                        let _no = clipboard.write_text(&import_string);
                    } else {
                        //TODO: Notifications
                    }
                }
            >
                "Copy to Clipboard"
            </button>

            <div class="flex gap-2 mt-3">
                <div class="card bg-base-100 shadow-xl w-full text-left">
                    <div class="card-body">
                        <h2 class="card-title">"Import to Quizlet"</h2>
                        <ol class="px-4">
                            <li>"Copy the generated data using the Copy Button on the WebPage"</li>
                            <li>"Open the "<a href="https://quizlet.com/" class="link-primary">"Quizlet webpage"</a>" and within your 'Study Set' or 'Unidad de Estudio' click on Import"</li>
                            <li>"Paste the data generated by the program"</li>
                            <li class="font-bold">"On the Between term and definition field, you have to enter /#*#/"</li>
                            <li class="font-bold">"On the Between cards field, you have to enter \\n\\#\\n"</li>
                            <li>"Click on Import"</li>
                            <li>"Enjoy your flashcards!"</li>
                        </ol>
                        <div class="card-actions justify-end">
                            <a href="/faq" class="btn btn-primary">"See FAQ for Details"</a>
                        </div>
                    </div>
                </div>

                <div class="card bg-base-100 shadow-xl w-full text-left">
                    <div class="card-body">
                        <h2 class="card-title">"Import to Vaia"</h2>
                        <ol class="px-4">
                            <li>"Copy the generated data using the Copy Button on the WebPage"</li>
                            <li>"Open the "<a href="https://app.vaia.com/home" class="link-primary">"StudySmarter(Vaia) webpage"</a>" and within your 'Study Set' or 'Unidad de Estudio' click on the three dots at the top right corner and click on 'Import Flashcards'"</li>
                            <li>"Click on Import"</li>
                            <li>"Enjoy your flashcards!"</li>
                        </ol>
                        <div class="card-actions justify-end">
                            <a href="/faq" class="btn btn-primary">"See FAQ for Details"</a>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    }
}
